# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
      # -   id: check-added-large-files

    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.5.6
      hooks:
          # Run the linter.
          - id: ruff
            args: [--fix]
          # Run the formatter.
          - id: ruff-format

    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort
            name: isort (python)

    # - repo: local
    #   hooks:
    #       - id: astro-parse
    #         name: astro-parse
    #         entry: astro dev parse
    #         language: system
    #         pass_filenames: false
    #         always_run: true
    # - repo: local
    #   hooks:
    #       - id: astro-pytest
    #         name: astro-pytest-check
    #         entry: astro dev pytest
    #         language: system
    #         pass_filenames: false
    #         always_run: true
